### ISSUE TITLE
Very prolonged build time

### ISSUE THREAD

**Issue by UBogun** [UBogun/Xojo-iosLib#1]
In Xojo 2014r3.1, building this project takes an enormous lot of time when building the animation demo views. Compilation time for debugging is fast as usual. But please do not take to animation views as templates for your own project therefore.

**Comment by UBogun** [comment]
No problem for the rewritten lib anymore

**Comment by aobs** [comment]
das neue ioslib stürtzt unter 64bit immer noch ab

**Comment by UBogun** [comment]
Laut Xojo-Forum funktioniert es auf dem iPhone6. Auf welchem Gerät geht es nicht? Mit welcher Fehlermeldung/Crashlog?

**Comment by aobs** [comment]
iphone5s

crashlog schick ich dir

von unterwegs versendet
