### ISSUE TITLE
Runtime error: Universal/CppExtras.h

### ISSUE THREAD

**Issue by sworteu** [UBogun/Xojo-iosLib#56]
If i run a project which has iOSLib in it i get this error:

Runtime error: 
Location: Universal/CppExtras.h:73
Condition: down != nullptr
Message: 19DrawableCocoaBitmap

I have no clue where it comes from or where to find it.

**Comment by UBogun** [comment]
This sounds like something in the code structure could have been messed up. Did you accidentally drag the library folder into the project instead of copying it? What happens when you download the latest version and run the intro project?

**Comment by sworteu** [comment]
It has already been fixed i noticed. It happens when you drag the library (folder) into the project.

**Comment by UBogun** [comment]
Yes, that’s what I recommended earlier but once a drag import exceeds a certain size or complexity, it can lead to unexpected results. Copy via clipboard is safe.
Thanks for notifying! I’ll close this issue then.
